Develop merge to master
TaranCorp/MedicalCenter pull request #14
Opened 2021-05-08 11:51 UTC by matiwei

According to decision made on last meeting (we are switching to trunk-based development) - merged develop to master

2021-05-08 18:29 UTC, alexeidb9 requested changes
Nie widzę konfliktów, można mergować, ale jeszcze poczekać można do poniedziałku, i już bedziemy mieli readme, inni coś wypchną za weekend :)

2021-05-08 18:29 UTC, alxndrpro commented on diagrams/Diagram-MedicalCenter.drawio
> +<mxfile host="app.diagrams.net" modified="2021-04-28T14:20:08.872Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" etag="gkca55H9PI
Myślię można pozbyć tych diagram na repo, bym było mniej "smieci".

2021-05-08 18:29 UTC, alxndrpro commented on src/main/java/com/javateam/medicalcenter/Domain.java
> +//        Employee asd = context.getBean(17, "Dorota", "Szeremet", 333444555, 12-07-1984,
Chyba te moję zakomentowane proby programmu bez sensu i tylko przeszkadzaja.

2021-05-09 18:27 UTC, oopalinska approved these changes, later dismissed

2021-05-10 18:40 UTC, alxndrpro submitted a review, later dismissed

2021-05-16 14:47 UTC, alexeidb9 commented
Na co chciałbym jeszcze zwroćić uwage, to że można przed pull'em bardziej czytelnie uporządkować wszystkie commity.

2021-05-25 13:22 UTC, oopalinska approved these changes

2021-05-25 13:24 UTC, oopalinska approved these changes

2021-05-25 13:47 UTC, alexeidb9 approved these changes

2021-05-25 13:47 UTC, merged